let
  # Fetch a specific version of nixpkgs with known compatibility
  nixpkgs = import (fetchTarball {
    url = "https://github.com/NixOS/nixpkgs/archive/nixos-23.05.tar.gz";
  }) {
    overlays = [
      (self: super: {
        beamPackages = super.beam.packages.erlang;
      })
    ];
  };
in

nixpkgs.beamPackages.mixRelease {
  pname = "my-elixir-app";
  version = "0.1.0";

  src = ./.;

  # Load dependencies generated by mix2nix
  mixDeps = import ./mix-deps.nix;

  # Define build inputs for beam package
  beamPackage = {
    buildInputs = [ nixpkgs.elixir nixpkgs.erlang ];
  };
}
